:verbose: false
:concurrency: 10


# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 8


:queues:
  - critical
  - mailer
  - default


production:
  :concurrency: 25

staging:
  :concurrency: 15
